### ISSUE TITLE
Client SSL handshake failed - no cipher suites in common

### ISSUE THREAD

**Issue by tiavx** [knoobdev/Bypass-Facebook-SLL-Pinning#2]
I'm getting "Client SSL handshake failed - no cipher suites in common" error after replacing the library using Charles Proxy or any other software.  What can be wrong?

Thanks

**Comment by knoobdev** [comment]
U can using Burpsuite

**Comment by tiavx** [comment]
Does the proxy require any special setting?

**Comment by Bnaya** [comment]
@knoobdev 
Here's some errors from logcat that i think that related:
```
07-22 07:26:17.161  5380  5577 E ExoPlayerImplInternal: Internal track renderer error.
07-22 07:26:17.161  5380  5577 E ExoPlayerImplInternal: X.6M8: X.2tK: X.2tK: TigonError(2): TigonLigerErrorDomain(15) Shutdown transport: ConnectionReset AsyncSocketException: St13runtime_error: received alert: handshake_failure, in state ExpectingServerHello, type = SSL error, 10.0.3.2:8888
07-22 07:26:17.161  5380  5577 E ExoPlayerImplInternal: 	at X.2mM.L(:668540)
07-22 07:26:17.161  5380  5577 E ExoPlayerImplInternal: 	at X.2qF.handleMessage(:681111)
07-22 07:26:17.161  5380  5577 E ExoPlayerImplInternal: 	at android.os.Handler.dispatchMessage(Handler.java:98)
07-22 07:26:17.161  5380  5577 E ExoPlayerImplInternal: 	at android.os.Looper.loop(Looper.java:148)
07-22 07:26:17.161  5380  5577 E ExoPlayerImplInternal: 	at android.os.HandlerThread.run(HandlerThread.java:61)
07-22 07:26:17.161  5380  5577 E ExoPlayerImplInternal: Caused by: X.2tK: X.2tK: TigonError(2): TigonLigerErrorDomain(15) Shutdown transport: ConnectionReset AsyncSocketException: St13runtime_error: received alert: handshake_failure, in state ExpectingServerHello, type = SSL error, 10.0.3.2:8888
07-22 07:26:17.161  5380  5577 E ExoPlayerImplInternal: 	at X.2po.TSC(:678413)
07-22 07:26:17.161  5380  5577 E ExoPlayerImplInternal: 	at X.2pr.TSC(:678667)
07-22 07:26:17.161  5380  5577 E ExoPlayerImplInternal: 	at X.2pt.E(:678938)
07-22 07:26:17.161  5380  5577 E ExoPlayerImplInternal: 	at X.2pt.TSC(:679056)
07-22 07:26:17.161  5380  5577 E ExoPlayerImplInternal: 	at X.6Mq.E(:1254524)
07-22 07:26:17.161  5380  5577 E ExoPlayerImplInternal: 	at X.6Mq.ZNB(:1254534)
07-22 07:26:17.161  5380  5577 E ExoPlayerImplInternal: 	at X.6OQ.run(:1258625)
07-22 07:26:17.161  5380  5577 E ExoPlayerImplInternal: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
07-22 07:26:17.161  5380  5577 E ExoPlayerImplInternal: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
07-22 07:26:17.161  5380  5577 E ExoPlayerImplInternal: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
07-22 07:26:17.161  5380  5577 E ExoPlayerImplInternal: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
07-22 07:26:17.161  5380  5577 E ExoPlayerImplInternal: 	at java.lang.Thread.run(Thread.java:818)
07-22 07:26:17.161  5380  5577 E ExoPlayerImplInternal: Caused by: X.2tK: TigonError(2): TigonLigerErrorDomain(15) Shutdown transport: ConnectionReset AsyncSocketException: St13runtime_error: received alert: handshake_failure, in state ExpectingServerHello, type = SSL error, 10.0.3.2:8888
07-22 07:26:17.161  5380  5577 E ExoPlayerImplInternal: 	at X.2po.TSC(:678437)
07-22 07:26:17.161  5380  5577 E ExoPlayerImplInternal: 	... 11 more
07-22 07:26:17.161  5380  5577 E ExoPlayerImplInternal: Caused by: com.facebook.tigon.tigonutils.TigonErrorException: TigonError(2): TigonLigerErrorDomain(15) Shutdown transport: ConnectionReset AsyncSocketException: St13runtime_error: received alert: handshake_failure, in state ExpectingServerHello, type = SSL error, 10.0.3.2:8888
07-22 07:26:17.161  5380  5577 E ExoPlayerImplInternal: 	at X.2q2.onError(:679558)
07-22 07:26:17.161  5380  5577 E ExoPlayerImplInternal: 	at X.2q1.onError(:679294)
07-22 07:26:17.161  5380  5577 E ExoPlayerImplInternal: 	at com.facebook.tigon.tigonapi.TigonCallbacksIntegerBufferJavaHelper.onError(:151509)
07-22 07:26:17.161  5380  5577 E ExoPlayerImplInternal: 	at com.facebook.common.jniexecutors.NativeRunnable.run(Native Method)
07-22 07:26:17.161  5380  5577 E ExoPlayerImplInternal: 	at com.facebook.common.jniexecutors.PooledNativeRunnable.run(:145866)
07-22 07:26:17.161  5380  5577 E ExoPlayerImplInternal: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
07-22 07:26:17.161  5380  5577 E ExoPlayerImplInternal: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
07-22 07:26:17.161  5380  5577 E ExoPlayerImplInternal: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
07-22 07:26:17.161  5380  5577 E ExoPlayerImplInternal: 	... 3 more
07-22 07:26:17.165  5270  5403 E fb4a.FbHeroPlayerLogger: HeroPlayer error[X.2tK: X.2tK: TigonError(2): TigonLigerErrorDomain(15) Shutdown transport: ConnectionReset AsyncSocketException: St13runtime_error: received alert: handshake_failure, in state ExpectingServerHello, type = SSL error, 10.0.3.2:8888] playerType[INLINE_PLAYER] videoId[2324269700927361]
07-22 07:26:17.166  5270  5403 E fb4a.VideoLoggingUtils: reason: HeroPlayer error:X.2tK: X.2tK: TigonError(2): TigonLigerErrorDomain(15) Shutdown transport: ConnectionReset AsyncSocketException: St13runtime_error: received alert: handshake_failure, in state ExpectingServerHello, type = SSL error, 10.0.3.2:8888
07-22 07:26:17.797  5270  5376 W fb4a.RequestLoggingListener: time 1449015: onProducerFinishWithFailure: {requestId: 56, stage: NetworkFetchProducer, elapsedTime: -1 ms, extraMap: null, throwable: com.facebook.tigon.tigonutils.TigonErrorException: TigonError(3): TigonLigerErrorDomain(20) received alert: handshake_failure, in state ExpectingServerHello}
07-22 07:26:17.797  5270  5376 W fb4a.RequestLoggingListener: com.facebook.tigon.tigonutils.TigonErrorException: TigonError(3): TigonLigerErrorDomain(20) received alert: handshake_failure, in state ExpectingServerHello
07-22 07:26:17.797  5270  5376 W fb4a.RequestLoggingListener: 	at X.0pT.onError(:149491)
07-22 07:26:17.797  5270  5376 W fb4a.RequestLoggingListener: 	at com.facebook.tigon.tigonapi.TigonCallbacksIntegerBufferJavaHelper.onError(:151509)
07-22 07:26:17.797  5270  5376 W fb4a.RequestLoggingListener: 	at com.facebook.common.jniexecutors.NativeRunnable.run(Native Method)
07-22 07:26:17.797  5270  5376 W fb4a.RequestLoggingListener: 	at com.facebook.common.jniexecutors.PooledNativeRunnable.run(:145866)
07-22 07:26:17.797  5270  5376 W fb4a.RequestLoggingListener: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
07-22 07:26:17.797  5270  5376 W fb4a.RequestLoggingListener: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
07-22 07:26:17.797  5270  5376 W fb4a.RequestLoggingListener: 	at X.0qN.run(:151467)
07-22 07:26:17.797  5270  5376 W fb4a.RequestLoggingListener: 	at java.lang.Thread.run(Thread.java:818)
07-22 07:26:17.798  5270  5376 W fb4a.RequestLoggingListener: time 1449015: onRequestFailure: {requestId: 56, elapsedTime: -1 ms, throwable: com.facebook.tigon.tigonutils.TigonErrorException: TigonError(3): TigonLigerErrorDomain(20) received alert: handshake_failure, in state ExpectingServerHello}
07-22 07:26:17.798  5270  5376 W fb4a.RequestLoggingListener: time 1449016: onRequestFailure: {requestId: 57, elapsedTime: -1 ms, throwable: com.facebook.tigon.tigonutils.TigonErrorException: TigonError(3): TigonLigerErrorDomain(20) received alert: handshake_failure, in state ExpectingServerHello}
07-22 07:26:17.798  5270  5376 W fb4a.RequestLoggingListener: time 1449016: onRequestFailure: {requestId: 58, elapsedTime: -1 ms, throwable: com.facebook.tigon.tigonutils.TigonErrorException: TigonError(3): TigonLigerErrorDomain(20) received alert: handshake_failure, in state ExpectingServerHello}
07-22 07:26:17.798  5270  5376 W fb4a.RequestLoggingListener: time 1449016: onRequestFailure: {requestId: 59, elapsedTime: -1 ms, throwable: com.facebook.tigon.tigonutils.TigonErrorException: TigonError(3): TigonLigerErrorDomain(20) received alert: handshake_failure, in state ExpectingServerHello}
07-22 07:26:17.855  5270  5376 W fb4a.RequestLoggingListener: time 1449073: onProducerFinishWithFailure: {requestId: 47, stage: NetworkFetchProducer, elapsedTime: -1 ms, extraMap: null, throwable: com.facebook.tigon.tigonutils.TigonErrorException: TigonError(3): TigonLigerErrorDomain(20) received alert: handshake_failure, in state ExpectingServerHello}
07-22 07:26:17.855  5270  5376 W fb4a.RequestLoggingListener: com.facebook.tigon.tigonutils.TigonErrorException: TigonError(3): TigonLigerErrorDomain(20) received alert: handshake_failure, in state ExpectingServerHello
07-22 07:26:17.855  5270  5376 W fb4a.RequestLoggingListener: 	at X.0pT.onError(:149491)
07-22 07:26:17.855  5270  5376 W fb4a.RequestLoggingListener: 	at com.facebook.tigon.tigonapi.TigonCallbacksIntegerBufferJavaHelper.onError(:151509)
07-22 07:26:17.855  5270  5376 W fb4a.RequestLoggingListener: 	at com.facebook.common.jniexecutors.NativeRunnable.run(Native Method)
07-22 07:26:17.855  5270  5376 W fb4a.RequestLoggingListener: 	at com.facebook.common.jniexecutors.PooledNativeRunnable.run(:145866)
07-22 07:26:17.855  5270  5376 W fb4a.RequestLoggingListener: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
07-22 07:26:17.855  5270  5376 W fb4a.RequestLoggingListener: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
07-22 07:26:17.855  5270  5376 W fb4a.RequestLoggingListener: 	at X.0qN.run(:151467)
07-22 07:26:17.855  5270  5376 W fb4a.RequestLoggingListener: 	at java.lang.Thread.run(Thread.java:818)
07-22 07:26:17.856  5270  5376 W fb4a.RequestLoggingListener: time 1449073: onRequestFailure: {requestId: 47, elapsedTime: -1 ms, throwable: com.facebook.tigon.tigonutils.TigonErrorException: TigonError(3): TigonLigerErrorDomain(20) received alert: handshake_failure, in state ExpectingServerHello}
07-22 07:26:17.861  5270  5376 W fb4a.RequestLoggingListener: time 1449079: onProducerFinishWithFailure: {requestId: 46, stage: NetworkFetchProducer, elapsedTime: -1 ms, extraMap: null, throwable: com.facebook.tigon.tigonutils.TigonErrorException: TigonError(3): TigonLigerErrorDomain(20) received alert: handshake_failure, in state ExpectingServerHello}
07-22 07:26:17.861  5270  5376 W fb4a.RequestLoggingListener: com.facebook.tigon.tigonutils.TigonErrorException: TigonError(3): TigonLigerErrorDomain(20) received alert: handshake_failure, in state ExpectingServerHello
07-22 07:26:17.861  5270  5376 W fb4a.RequestLoggingListener: 	at X.0pT.onError(:149491)
07-22 07:26:17.861  5270  5376 W fb4a.RequestLoggingListener: 	at com.facebook.tigon.tigonapi.TigonCallbacksIntegerBufferJavaHelper.onError(:151509)
07-22 07:26:17.861  5270  5376 W fb4a.RequestLoggingListener: 	at com.facebook.common.jniexecutors.NativeRunnable.run(Native Method)
07-22 07:26:17.861  5270  5376 W fb4a.RequestLoggingListener: 	at com.facebook.common.jniexecutors.PooledNativeRunnable.run(:145866)
07-22 07:26:17.861  5270  5376 W fb4a.RequestLoggingListener: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
07-22 07:26:17.861  5270  5376 W fb4a.RequestLoggingListener: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
07-22 07:26:17.861  5270  5376 W fb4a.RequestLoggingListener: 	at X.0qN.run(:151467)
07-22 07:26:17.861  5270  5376 W fb4a.RequestLoggingListener: 	at java.lang.Thread.run(Thread.java:818)
07-22 07:26:17.861  5270  5376 W fb4a.RequestLoggingListener: time 1449079: onRequestFailure: {requestId: 46, elapsedTime: -1 ms, throwable: com.facebook.tigon.tigonutils.TigonErrorException: TigonError(3): TigonLigerErrorDomain(20) received alert: handshake_failure, in state ExpectingServerHello}
07-22 07:26:17.865  5270  5376 W fb4a.RequestLoggingListener: time 1449082: onProducerFinishWithFailure: {requestId: 45, stage: NetworkFetchProducer, elapsedTime: -1 ms, extraMap: null, throwable: com.facebook.tigon.tigonutils.TigonErrorException: TigonError(3): TigonLigerErrorDomain(20) received alert: handshake_failure, in state ExpectingServerHello}
07-22 07:26:17.865  5270  5376 W fb4a.RequestLoggingListener: com.facebook.tigon.tigonutils.TigonErrorException: TigonError(3): TigonLigerErrorDomain(20) received alert: handshake_failure, in state ExpectingServerHello
07-22 07:26:17.865  5270  5376 W fb4a.RequestLoggingListener: 	at X.0pT.onError(:149491)
07-22 07:26:17.865  5270  5376 W fb4a.RequestLoggingListener: 	at com.facebook.tigon.tigonapi.TigonCallbacksIntegerBufferJavaHelper.onError(:151509)
07-22 07:26:17.865  5270  5376 W fb4a.RequestLoggingListener: 	at com.facebook.common.jniexecutors.NativeRunnable.run(Native Method)
07-22 07:26:17.865  5270  5376 W fb4a.RequestLoggingListener: 	at com.facebook.common.jniexecutors.PooledNativeRunnable.run(:145866)
07-22 07:26:17.865  5270  5376 W fb4a.RequestLoggingListener: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
07-22 07:26:17.865  5270  5376 W fb4a.RequestLoggingListener: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
07-22 07:26:17.865  5270  5376 W fb4a.RequestLoggingListener: 	at X.0qN.run(:151467)
07-22 07:26:17.865  5270  5376 W fb4a.RequestLoggingListener: 	at java.lang.Thread.run(Thread.java:818)
07-22 07:26:17.865  5270  5376 W fb4a.RequestLoggingListener: time 1449083: onRequestFailure: {requestId: 45, elapsedTime: -1 ms, throwable: com.facebook.tigon.tigonutils.TigonErrorException: TigonError(3): TigonLigerErrorDomain(20) received alert: handshake_failure, in state ExpectingServerHello}
07-22 07:26:17.891  5270  5376 W fb4a.RequestLoggingListener: time 1449109: onProducerFinishWithFailure: {requestId: 44, stage: NetworkFetchProducer, elapsedTime: -1 ms, extraMap: null, throwable: com.facebook.tigon.tigonutils.TigonErrorException: TigonError(3): TigonLigerErrorDomain(20) received alert: handshake_failure, in state ExpectingServerHello}
07-22 07:26:17.891  5270  5376 W fb4a.RequestLoggingListener: com.facebook.tigon.tigonutils.TigonErrorException: TigonError(3): TigonLigerErrorDomain(20) received alert: handshake_failure, in state ExpectingServerHello
07-22 07:26:17.891  5270  5376 W fb4a.RequestLoggingListener: 	at X.0pT.onError(:149491)
07-22 07:26:17.891  5270  5376 W fb4a.RequestLoggingListener: 	at com.facebook.tigon.tigonapi.TigonCallbacksIntegerBufferJavaHelper.onError(:151509)
07-22 07:26:17.891  5270  5376 W fb4a.RequestLoggingListener: 	at com.facebook.common.jniexecutors.NativeRunnable.run(Native Method)
07-22 07:26:17.891  5270  5376 W fb4a.RequestLoggingListener: 	at com.facebook.common.jniexecutors.PooledNativeRunnable.run(:145866)
07-22 07:26:17.891  5270  5376 W fb4a.RequestLoggingListener: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
07-22 07:26:17.891  5270  5376 W fb4a.RequestLoggingListener: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
07-22 07:26:17.891  5270  5376 W fb4a.RequestLoggingListener: 	at X.0qN.run(:151467)
07-22 07:26:17.891  5270  5376 W fb4a.RequestLoggingListener: 	at java.lang.Thread.run(Thread.java:818)
07-22 07:26:17.892  5270  5376 W fb4a.RequestLoggingListener: time 1449110: onRequestFailure: {requestId: 44, elapsedTime: -1 ms, throwable: com.facebook.tigon.tigonutils.TigonErrorException: TigonError(3): TigonLigerErrorDomain(20) received alert: handshake_failure, in state ExpectingServerHello}
07-22 07:26:37.739   586  4688 D NetlinkSocketObserver: NeighborEvent{elapsedMs=1468957, 10.0.3.2, [525400123502], RTM_NEWNEIGH, NUD_STALE}
07-22 07:26:44.769   586  1186 D Sensors : batch handle 6, but there is no batch sensor in genymotion
07-22 07:26:44.779   586  1118 I AccountManagerService: getTypesVisibleToCaller: isPermitted? true
07-22 07:26:44.783   901  5601 I AsyncOpDispatcher: 35-GetDeviceDataUploadOptInStatusOperation
07-22 07:26:44.794   586   674 D PressureSensor: pressure event 1013.000000
07-22 07:26:55.335   901  2185 W ctxmgr  : [AclManager]No 2 for (accnt=account#-517948760#, com.google.android.gms(10060):IndoorOutdoorProducer, vrsn=12685000, 0, 3pPkg = null ,  3pMdlId = null ,  pid = 901). Was: 3 for 57, account#-517948760#
07-22 07:27:10.138   586  4688 D NetlinkSocketObserver: NeighborEvent{elapsedMs=1501356, 10.0.3.2, [525400123502], RTM_NEWNEIGH, NUD_PROBE}
07-22 07:27:10.139   586  4688 D NetlinkSocketObserver: NeighborEvent{elapsedMs=1501357, 10.0.3.2, [525400123502], RTM_NEWNEIGH, NUD_REACHABLE}

```

The same setup works for me with older versions of the apk & coldstart

**Comment by hardcoder80** [comment]
Any updates?
